### ISSUE TITLE
No License?

### ISSUE THREAD

**Issue by jerlendds** [GONZOsint/gvision#4]
Hi, this looks awesome, Id love to fork and turn this into a library I can use with my osintbuddy project eventually but I see there's no license so I'm not able to decide if I can use this. Would you consider adding a license? (this is a nice resource: https://choosealicense.com/)

**Comment by PierrunoYT** [comment]
you can use the original from me

**Comment by GONZOsint** [comment]
@jerlendds LICENSE added. Thanks!
